INSERT INTO category(category_name) values('Mexican')
INSERT INTO category(category_name) values('Italian')
INSERT INTO category(category_name) values('American')
INSERT INTO category(category_name) values('Fast Food')
INSERT INTO category(category_name) values('Dip')
INSERT INTO category(category_name) values('Vegan')
INSERT INTO category(category_name) values('Avocado')
INSERT INTO category(category_name) values('Dinner')
INSERT INTO category(category_name) values('Grill')
INSERT INTO category(category_name) values('Quick and easy')
INSERT INTO category(category_name) values('Chicken')
INSERT INTO unit_of_measure(uom) values('Teaspoon')
INSERT INTO unit_of_measure(uom) values('Tablespoon')
INSERT INTO unit_of_measure(uom) values('Cut')
INSERT INTO unit_of_measure(uom) values('Dash')
INSERT INTO unit_of_measure(uom) values('Ounce')
INSERT INTO unit_of_measure(uom) values('Pounds')